	imglist = new Array();

	//各種目共通画像
	imglist.flogo = '<img src="../common_aute/images/flogo.gif" alt="au損害保険株式会社" />'
	imglist.no1 = '<img src="../common_aute/images/no1.png">'
	imglist.no2 = '<img src="../common_aute/images/no2.png">'
	imglist.no3 = '<img src="../common_aute/images/no3.png">'
	imglist.no4 = '<img src="../common_aute/images/no4.png">'
	imglist.no5 = '<img src="../common_aute/images/no5.png">'
	imglist.ico_arr = '<img class="ico_arr" alt="→" src="../lp/t_1_l/img/pc/ico_arr.png">'
	imglist.pdf_icon = '<img src="../pet/common/images/common/pdf_icon.png" alt="pdf"/></p>'
	imglist.copylight = '<img src="../common/spimg3/images_pet/copylight.png" alt="au損害保険株式会社">'
	imglist.btn_footer = '<img src="../common_aute/images/btn_footer.png" alt="au損保トップ">'
	imglist.blank_title = '<img src="../common_aute/images/blank_title.gif" alt="外部リンク" class="blankimg" />'
	imglist.back_to_top = '<img src="../common_aute/images3/back_to_top.png" alt="このページの先頭へ" />'
	imglist.img_hoshonaiyou = '<img src="../common_aute/images3/img_hoshonaiyou.jpg" alt="補償内容・保険料はこちら" />'
	imglist.img_point = '<img src="../common_aute/images3/img_point.png" alt="" style="width:20px;"/>'
	imglist.pc_logo_aute = '<img src="../common_aute/images/logo.gif" alt="「あうて」 あんしん・うれしい・ていねい" />'
	imglist.pc_index_contact2 = '<img src="../common_aute/images3/img_index_contact2.png" alt="カスタマーセンター受付時間拡大中" />'
	imglist.pc_plan_top01 = '<img alt="ペットの保険" src="../common_aute/images3/plan_top01.png">'
	imglist.pc_plan_top02 = '<img alt="ケガの保険 Bycle" src="../common_aute/images3/plan_top02.png">'
	imglist.pc_plan_top03 = '<img alt="ケガの保険 交通事故" src="../common_aute/images3/plan_top03.png">'
	imglist.pc_plan_top04 = '<img alt="ケガの保険 日常の事故" src="../common_aute/images3/plan_top04.png">'
	imglist.pc_plan_top05 = '<img alt="旅行の保険 海外旅行" src="../common_aute/images3/plan_top05.png">'
	imglist.pc_plan_top06 = '<img alt="旅行の保険 国内旅行" src="../common_aute/images3/plan_top06.png">'
	imglist.pc_plan_top07 = '<img alt="ゴルフの保険" src="../common_aute/images3/plan_top07.png">'
	imglist.pc_plan_top01_on = '<img alt="ペットの保険" src="../common_aute/images3/plan_top01_on.png">'
	imglist.pc_plan_top02_on = '<img alt="ケガの保険 Bycle" src="../common_aute/images3/plan_top02_on.png">'
	imglist.pc_plan_top03_on = '<img alt="ケガの保険 交通事故" src="../common_aute/images3/plan_top03_on.png">'
	imglist.pc_plan_top04_on = '<img alt="ケガの保険 日常の事故" src="../common_aute/images3/plan_top04_on.png">'
	imglist.pc_plan_top05_on = '<img alt="旅行の保険 海外旅行" src="../common_aute/images3/plan_top05_on.png">'
	imglist.pc_plan_top06_on = '<img alt="旅行の保険 国内旅行" src="../common_aute/images3/plan_top06_on.png">'
	imglist.pc_plan_top07_on = '<img alt="ゴルフの保険" src="../common_aute/images3/plan_top07_on.png">'
	imglist.pc_gnav_home = '<img src="../common_aute/images/gnav_home.jpg" alt="HOME" class="imgover" />'
	imglist.pc_gnav_item_o = '<img src="../common_aute/images/gnav_item_o.jpg" alt="商品のご紹介" />'
	imglist.pc_pulldown_goods01 = '<img src="../common_aute/images/pulldown_goods01.png" alt="ケガの保険 Bycle" class="imgover" />'
	imglist.pc_pulldown_goods03 = '<img src="../common_aute/images/pulldown_goods03.png" alt="ケガの保険 交通事故" class="imgover" />'
	imglist.pc_pulldown_goods04 = '<img src="../common_aute/images/pulldown_goods04.png" alt="ケガの保険 日常の事故" class="imgover" />'
	imglist.pc_pulldown_goods06 = '<img src="../common_aute/images/pulldown_goods06.png" alt="旅行の保険 海外" class="imgover" />'
	imglist.pc_pulldown_goods08 = '<img src="../common_aute/images/pulldown_goods08.png" alt="旅行の保険 国内" class="imgover" />'
	imglist.pc_pulldown_goods07 = '<img src="../common_aute/images/pulldown_goods07.png" alt="ゴルフの保険" class="imgover" />'
	imglist.pc_pulldown_goods09 = '<img src="../common_aute/images/pulldown_goods09.png" alt="ペットの保険" class="imgover" />'
	imglist.pc_gnav_about = '<img src="../common_aute/images/gnav_about.jpg" alt="「あうて」について" class="imgover" />'
	imglist.pc_pulldown_about01 = '<img src="../common_aute/images/pulldown_about01.png" alt="保険の申込みについて" class="imgover" />'
	imglist.pc_pulldown_about02 = '<img src="../common_aute/images/pulldown_about02.png" alt="継続のお手続き" class="imgover" />'
	imglist.pc_gnav_accident = '<img src="../common_aute/images/gnav_accident.jpg" alt="事故のお手続き" class="imgover" />'
	imglist.pc_pulldown_jiko01 = '<img src="../common_aute/images/pulldown_jiko01.png" alt="事故のご連絡" class="imgover" />'
	imglist.pc_pulldown_jiko02 = '<img src="../common_aute/images/pulldown_jiko02.png" alt="保険金のお受取りまで" class="imgover" />'
	imglist.pc_gnav_faq = '<img src="../common_aute/images/gnav_faq.jpg" alt="Q＆A・お問い合わせ" class="imgover" />'
	imglist.pc_pulldown_qa01 = '<img src="../common_aute/images/pulldown_qa01.png" alt="Ｑ＆Ａ(よくあるご質問) " class="imgover" />'
	imglist.pc_pulldown_qa02 = '<img src="../common_aute/images/pulldown_qa02.png" alt="お問い合わせ" class="imgover" />'
	imglist.pc_bnr_standard = '<img src="../common_aute/images3/bnr_standard.gif" alt="スタンダード傷害保険" class="ins-bnr" />'
	imglist.pc_bnr_kaigaisongai = '<img src="../common_aute/images3/bnr_kaigaisongai.gif" alt="海外旅行保険" class="ins-bnr" />'
	
	//PCのみ　サイドバー関連
	imglist.right_userpage_header = '<img src="../common_aute/images3/right_container/right_userpage_header.png" alt="お客さま専用ページ" />'
	imglist.right_btn_login = '<img src="../common_aute/images3/right_container/right_btn_login.png" alt="ログイン" class="imgover" />'
	imglist.right_img_contact = '<img src="../common_aute/images3/right_container/right_img_contact.png" alt="お問い合わせ" class="customerIamge" />'
	imglist.right_provision_header = '<img src="../common_aute/images3/right_container/right_provision_header.png" alt="重要事項説明書・約款" />'
	imglist.right_btn_application_kaigai = '<img src="../common_aute/images3/right_container/right_btn_application_kaigai.gif" alt="あうて「旅行の保険 海外旅行」お申込みはこちら" class="hover_opacity" />'
	imglist.right_print_header = '<img src="../common_aute/images3/right_container/right_print_header.png" alt="印刷" />'
	imglist.right_support_header = '<img src="../common_aute/images3/right_container/right_support_header.png" alt="海外サポートデスク" />'
	imglist.right_support_txt01 = '<img src="../common_aute/images3/right_container/right_support_txt01.png" alt="海外のご旅行先から" />'
	imglist.right_btn_support = '<img src="../common_aute/images3/right_container/right_btn_support.png" alt="番号一覧" class="imgover" />'
	imglist.right_support_txt02 = '<img src="../common_aute/images3/right_container/right_support_txt02.png" alt="日本国内から" />'

	//海外旅行
	imglist.img_kaigai01 = '<img src="../common_aute/images3/img_kaigai01.gif" alt="旅行の保険 海外旅行" class="mgb5 centerImage" style="width:60%;"/>'
	imglist.img_kaigai01_3 = '<img src="../common_aute/images3/img_kaigai01_3.gif" alt="例えば" class="mgb10 sp_img_98p" />'
	imglist.bt_app_kaigai = '<img src="../common_aute/images3/bt_app_kaigai.gif" alt="あうて「旅行の保険 海外旅行」お申込みはこちら" class="hover_opacity sp_img_90p" />'
	imglist.img_kaigai02 = '<img class="sp_img_98p" src="../common_aute/images3/img_kaigai02.jpg" alt="海外旅行に便利な無料アプリ「海外サポート」配信中！" style="margin:0 auto 10px;" id="kaigaiapl"/>'
	imglist.img_kaigai03_2 = '<img src="../common_aute/images3/img_kaigai03_2.gif" alt="楽しい海外旅行をサポート" width="100%" />'
	imglist.img_foreign16 = ''
	imglist.img_kaigai36 = '<img src="../common_aute/images3/img_kaigai36.gif" alt="" />'
	imglist.img_kaigai18 = '<img src="../common_aute/images3/img_kaigai18.jpg" alt="海外サポートデスク　24時間 365日  日本語で対応！" />'
	imglist.img_kaigai19 = '<img src="../common_aute/images3/img_kaigai19.jpg" alt="海外旅行でお困りのことがあればいつでもお電話ください" class="f-l" />'
	imglist.img_kaigai20 = '<img src="../common_aute/images3/img_kaigai20.jpg" alt="海外旅行でお困りのことがあればいつでもお電話ください" />'
	imglist.img_kaigai21 = '<img src="../common_aute/images3/img_kaigai21.jpg" alt="海外のご旅行先から ワールドフリーフォン番号一覧" class="imgover f-l" />'
	imglist.img_kaigai22 = '<img src="../common_aute/images3/img_kaigai22.jpg" alt="日本国内から　0077-78-7365（通話料無料）03-6365-8885（通話料お客さま負担）" class="f-r" />'
	imglist.img_kaigai23 = '<img src="../common_aute/images3/img_kaigai23.gif" alt="海外旅行保険「旅行の保険 海外旅行」なら提携医療機関ならキャッシュレスOK！" class="mgb15 display_pc" /><br />'
	imglist.img_kaigai25 = '<img src="../common_aute/images3/img_kaigai25.gif" alt="こんなトラブルをしっかりサポート！海外旅行保険「旅行の保険 海外旅行」" class="mgb30 display_pc" />'
	imglist.img_kaigai32 = '<img src="../common_aute/images3/img_kaigai32.jpg" alt="海外で病気やケガをした場合、治療費や入院費は、日本と比べるとはるかに高額になることもあります" class="mgb30" id="kaigaipremium" />'
	imglist.img_kaigai33 = '<img src="../common_aute/images3/img_kaigai33.gif" alt="例えばアメリカ（ニューヨーク）では…"/>'
