	imglist = new Array();

	//各種目共通画像
	imglist.flogo = '<img style="width:95%;" src="../common_aute/images/flogo.gif" alt="au損害保険株式会社">'
	imglist.no1 = '<img src="../common_aute/images/no1.png">'
	imglist.no2 = '<img src="../common_aute/images/no2.png">'
	imglist.no3 = '<img src="../common_aute/images/no3.png">'
	imglist.no4 = '<img src="../common_aute/images/no4.png">'
	imglist.no5 = '<img src="../common_aute/images/no5.png">'
	imglist.ico_arr = '<img class="ico_arr" alt="→" src="../lp/t_1_l/img/pc/ico_arr.png">'
	imglist.pdf_icon = '<img src="../pet/common/images/common/pdf_icon.png" alt="pdf"/></p>'
	imglist.sp_customer = '<img style="width: 80%; max-width:300px;margin-top:10px;" src="../common_aute/images/sp_customer.png" alt="お問い合わせ">'
	imglist.copylight = '<img src="../common/spimg3/images_pet/copylight.png" alt="au損害保険株式会社">'
	imglist.btn_footer = '<img src="../common_aute/images/btn_footer.png" alt="au損保トップ">'
	imglist.blank_title = '<img src="../common_aute/images/blank_title.gif" alt="外部リンク" class="blankimg" />'
	imglist.pc_bnr_standard = '<img src="../common_aute/images3/bnr_standard.gif" alt="スタンダード傷害保険" class="ins-bnr" style="width:110px;height:16px;"/>'
	imglist.pc_bnr_kaigaisongai = '<img src="../common_aute/images3/bnr_kaigaisongai.gif" alt="海外旅行保険" class="ins-bnr" style="width:110px;height:16px;"/>'
	imglist.img_point = '<img src="../common_aute/images3/img_point.png" alt="" style="width:20px;"/>'
	imglist.icon_company = '<img src="../common_aute/images3/icon_company.gif" alt="会社概要" style="height:18px;width:16px;" />'
	imglist.img_hoshonaiyou = '<img src="../common_aute/images3/img_hoshonaiyou.jpg" alt="補償内容・保険料はこちら" />'
	
	//SPのみ　ヘッダーとフッターとアコーディオン
	imglist.sp_logo_aute = '<img style="width:90%;margin:auto auto auto 0.1em;" src="../common_aute/images3/logo_aute.png" alt="あうて">'
	imglist.sp_flogo = '<img style="width:90%;" src="../common_aute/images/flogo.gif" alt="au損害保険株式会社">'
	imglist.sp_login = '<img style="width:100%;" src="../common/spimg3/images_pet/login.png" alt="ログイン">'
	imglist.sp_floating_navi = '<img style="width:100%;" src="../common/spimg3/images_pet/floating_navi.png" alt="メニュー" class="showNavi">'
	imglist.sp_icon_company = '<img src="../common_aute/images3/icon_company.gif" alt="会社概要" style="height:18px;width:16px;" />'
	imglist.accordion_01_open = '<img src="../common_aute/images3/images_accident/title_point01_open.gif" style="width:100%;" alt="交通事故によるケガを補償">'
	imglist.accordion_02_open = '<img src="../common_aute/images3/images_accident/title_point02_open.gif" style="width:100%;" alt="賠償責任補償は日常生活での事故も対象">'
	imglist.accordion_03_open = '<img src="../common_aute/images3/images_accident/title_point03_open.gif" style="width:100%;" alt="自転車ロードサービスもセット！">'
	imglist.accordion_01_close = '<img src="../common_aute/images3/images_accident/title_point01_close.gif" style="display:none;width:100%;" alt="交通事故によるケガを補償">'
	imglist.accordion_02_close = '<img src="../common_aute/images3/images_accident/title_point02_close.gif" style="display:none;width:100%;" alt="賠償責任補償は日常生活での事故も対象">'
	imglist.accordion_03_close = '<img src="../common_aute/images3/images_accident/title_point03_close.gif" style="display:none;width:100%;" alt="自転車ロードサービスもセット！">'

	//交通事故
	imglist.img_koutsuujiko01 = '<img src="../common_aute/images3/img_koutsuujiko01.gif" alt="あうて「ケガの保険 交通事故」" class="centerImage sp_img_90p" style="margin-top:-10px;" />'
	imglist.img_koutsuujiko02 = '<img class="sp_img_98p" src="../common_aute/images/img_accident02.gif" alt="例えば、こんな場合などに補償します" />'
	imglist.bt_app_koutsuujiko = '<img src="../common_aute/images3/bt_app_koutsuujiko.gif" alt="あうて「ケガの保険 交通事故」お申込みはこちら" class="hover_opacity sp_img_90p" />'
	imglist.img_koutsuujiko03 = '<img class="sp_img_98p" src="../common_aute/images/img_accident03.gif" alt="例えば、こんな場合などに補償します" />'
	imglist.plan_bycle_app02 = '<img src="../common_aute/images3/plan_bycle_app02.jpg" alt="自転車の日詳細はこちら" class="sp_img_90p" />'
	imglist.img_bycle06 = '<img src="../common_aute/images3/img_bycle06.jpg" alt="自転車ロードサービスもセット！" class="f-l" />'
	imglist.bt_detail = '<img src="../common_aute/images3/bt_detail.gif" alt="詳細をみる" class="imgover" />'
