	imglist = new Array();

	//各種目共通画像
	imglist.flogo = '<img style="width:95%;" src="../common_aute/images/flogo.gif" alt="au損害保険株式会社">'
	imglist.no1 = '<img src="../common_aute/images/no1.png">'
	imglist.no2 = '<img src="../common_aute/images/no2.png">'
	imglist.no3 = '<img src="../common_aute/images/no3.png">'
	imglist.no4 = '<img src="../common_aute/images/no4.png">'
	imglist.no5 = '<img src="../common_aute/images/no5.png">'
	imglist.ico_arr = '<img class="ico_arr" alt="→" src="../lp/t_1_l/img/pc/ico_arr.png">'
	imglist.pdf_icon = '<img src="../pet/common/images/common/pdf_icon.png" alt="pdf"/></p>'
	imglist.sp_customer = '<img style="width: 80%; max-width:300px;margin-top:10px;" src="../common_aute/images/sp_customer.png" alt="お問い合わせ">'
	imglist.copylight = '<img src="../common/spimg3/images_pet/copylight.png" alt="au損害保険株式会社">'
	imglist.btn_footer = '<img src="../common_aute/images/btn_footer.png" alt="au損保トップ">'
	imglist.blank_title = '<img src="../common_aute/images/blank_title.gif" alt="外部リンク" class="blankimg" />'
	imglist.pc_bnr_standard = '<img src="../common_aute/images3/bnr_standard.gif" alt="スタンダード傷害保険" class="ins-bnr" style="width:110px;height:16px;"/>'
	imglist.img_point = '<img src="../common_aute/images3/img_point.png" alt="" style="width:20px;"/>'
	imglist.icon_company = '<img src="../common_aute/images3/icon_company.gif" alt="会社概要" style="height:18px;width:16px;" />'
	
	//SPのみ　ヘッダーとフッターとアコーディオン
	imglist.sp_logo_aute = '<img style="width:90%;margin:auto auto auto 0.1em;" src="../common_aute/images3/logo_aute.png" alt="あうて">'
	imglist.sp_flogo = '<img style="width:90%;" src="../common_aute/images/flogo.gif" alt="au損害保険株式会社">'
	imglist.sp_login = '<img style="width:100%;" src="../common/spimg3/images_pet/login.png" alt="ログイン">'
	imglist.sp_floating_navi = '<img style="width:100%;" src="../common/spimg3/images_pet/floating_navi.png" alt="メニュー" class="showNavi">'
	imglist.sp_icon_company = '<img src="../common_aute/images3/icon_company.gif" alt="会社概要" style="height:18px;width:16px;" />'
	imglist.accordion_bycle01_open = '<img src="../common_aute/images3/images_bycle/title_point01_open.gif" style="width:100%;" alt="交通事故によるケガを補償、さらに自転車事故の場合は保険金が２倍！">'
	imglist.accordion_bycle02_open = '<img src="../common_aute/images3/images_bycle/title_point02_open.gif" style="width:100%;" alt="安心の示談代行サービス（賠償事故解決特約）">'
	imglist.accordion_bycle03_open = '<img src="../common_aute/images3/images_bycle/title_point03_open.gif" style="width:100%;" alt="個人賠償責任補償は自転車事故だけでなく日常生活中の賠償事故も対象">'
	imglist.accordion_bycle04_open = '<img src="../common_aute/images3/images_bycle/title_point04_open.gif" style="width:100%;" alt="自転車ロードサービスもセット！">'
	imglist.accordion_bycle01_close = '<img src="../common_aute/images3/images_bycle/title_point01_close.gif" style="display:none;width:100%;" alt="交通事故によるケガを補償、さらに自転車事故の場合は保険金が２倍！">'
	imglist.accordion_bycle02_close = '<img src="../common_aute/images3/images_bycle/title_point02_close.gif" style="display:none;width:100%;" alt="安心の示談代行サービス（賠償事故解決特約）">'
	imglist.accordion_bycle03_close = '<img src="../common_aute/images3/images_bycle/title_point03_close.gif" style="display:none;width:100%;" alt="個人賠償責任補償は自転車事故だけでなく日常生活中の賠償事故も対象">'
	imglist.accordion_bycle04_close = '<img src="../common_aute/images3/images_bycle/title_point04_close.gif" style="display:none;width:100%;" alt="自転車ロードサービスもセット！">'
	
	//bycle
	imglist.img_bycle01 = '<img src="../common_aute/images3/sp_img_bicle01_3.png" alt="自転車保険「Bycle（バイクル）」" class="centerImage sp_img_90p" />'
	imglist.bt_app_bycle = '<img class="hover_opacity sp_img_98p" src="../common_aute/images3/bt_app_bycle.gif" alt="あうて「ケガの保険 Bycle」お申込みはこちら" />'
	imglist.bt_app_bycle_2 = '<img class="hover_opacity" style="width:93%;" src="../common_aute/images3/bt_app_bycle.gif" alt="あうて「ケガの保険 Bycle」お申込みはこちら" />'
	imglist.img_bycle11 = '<img src="../common_aute/images3/img_bycle11.jpg" alt="交通事故によるケガを補償、さらに自転車事故の場合は保険金が２倍！" style="width: 100%;" />'
	imglist.img_bycle12 = '<img src="../common_aute/images3/img_bycle12.jpg" alt="万一加害事故を起こしてしまった場合でも示談代行サービスで安心" style="width: 100%;" />'
	imglist.img_bycle03 = '<img src="../common_aute/images3/img_bycle03.jpg" alt="安心の示談代行サービス" style="margin:0 auto;" />'
	imglist.img_bycle13 = '<img src="../common_aute/images3/img_bycle13.jpg" alt="個人賠償責任補償は自転車事故だけでなく日常生活中の賠償事故も対象" style="width: 100%;" />'
	imglist.img_bycle14 = '<img src="../common_aute/images3/img_bycle14.jpg" alt="自転車ロードサービスもセット！" style="width: 100%;" />'
	imglist.img_bycle02 = '<img class="sp_img_98p" style="margin: 0 auto;" src="../common_aute/images3/sp_img_bicle02.gif" alt="自転車保険「Bycle」なら自転車事故によるケガは保険金が2倍!!" />'
	imglist.img_bycle05 = '<img src="../common_aute/images3/sp_img_bicle04.gif" alt="例えば、こんな場合などに補償します" class="sp_img_98p" />'
	imglist.img_bycle06 = '<img src="../common_aute/images3/img_bycle06.jpg" alt="自転車ロードサービスもセット！" class="f-l" />'
	imglist.bt_detail = '<img src="../common_aute/images3/bt_detail.gif" alt="詳細をみる" class="imgover" />'
	imglist.casestudy = '<img src="../common_aute/images3/SP_casestudy.gif" alt="ケーススタディ" class="hover_opacity sp_img_98p" />'
	imglist.plan_bycle_app01 = '<img src="../common_aute/images3/sp_img_bicle19.gif" alt="自転車の日" class="display_block_sp sp_img_98p" style="margin: 0 auto 20px;" />'
	imglist.plan_bycle_app02 = '<img src="../common_aute/images3/plan_bycle_app02.jpg" alt="自転車の日詳細はこちら" class="sp_img_98p" />'
	imglist.img_down = '<img alt="自転車に係る事故の保険料はこの金額の2倍！！" src="../common_aute/images3/img_down.png" style="margin-top: 5px;height:20px;width:50px;">'

